Repository 100-hours-a-week/22-tenten-fe, pull requests merged in 2025-07, with the labels that each got.

#244 [FEAT] 채팅방 ui 구현
  kakaobase/public/roro.png
  kakaobase/src/app/chat/page.tsx
  kakaobase/src/app/post/[postId]/page.tsx
  kakaobase/src/features/chat/hooks/useMessageForm.tsx
  kakaobase/src/features/chat/ui/BotChat.tsx
  kakaobase/src/features/chat/ui/ChatList.tsx
  kakaobase/src/features/chat/ui/MessageInput.tsx
  kakaobase/src/features/chat/ui/MyChat.tsx
  kakaobase/src/features/feeds/comments/ui/CommentInput.tsx
  kakaobase/src/widgets/navbar/NavItem.tsx
Labels: FEAT

#247 [FEAT] 알림 관련 페이지 라우팅
  kakaobase/src/features/alarm/hooks/useAlarmRouting.tsx
  kakaobase/src/features/alarm/hooks/useAlarmSwipe.tsx
  kakaobase/src/features/alarm/lib/socket.tsx
  kakaobase/src/features/alarm/ui/AlarmAction.tsx
  kakaobase/src/features/alarm/ui/AlarmItem.tsx
Labels: FEAT

#248 [FIX] 알림 안정화
  kakaobase/src/app/providers.tsx
  kakaobase/src/features/alarm/hooks/useAlarm.tsx
  kakaobase/src/features/alarm/hooks/useAlarmSwipe.tsx
  kakaobase/src/features/alarm/lib/socket.tsx
  kakaobase/src/features/alarm/types/AlarmResponse.tsx
  kakaobase/src/features/alarm/ui/AlarmItem.tsx
  kakaobase/src/features/alarm/ui/AlarmList.tsx
Labels: FIX

#251 [FEAT] 서핑하는 춘식이 추가
  kakaobase/public/chunsik.png
  kakaobase/public/surfing.png
  kakaobase/public/void.webp
  kakaobase/src/app/globals.css
  kakaobase/src/app/layout.tsx
  kakaobase/src/shared/ui/Toast.tsx
  kakaobase/tailwind.config.ts
Labels: FEAT, DESIGN

#252 [FIX] 무한 새로고침 문제 해결
  kakaobase/src/shared/api/api.tsx
Labels: FIX

#255 [DESIGN] 게시글 작성 버튼 위치 변경
  kakaobase/src/app/main/page.tsx
  kakaobase/src/widgets/buttons/FloatingButtonGroup.tsx
Labels: FIX, DESIGN

#256 [FIX] 모바일에서 게시글 작성 버튼 보이게
  kakaobase/src/features/feeds/posts/ui/PostList.tsx
  kakaobase/src/widgets/buttons/FloatingButtonGroup.tsx
  kakaobase/src/widgets/buttons/GoNewPost.tsx
  kakaobase/src/widgets/buttons/GoUp.tsx
Labels: FIX, DESIGN

#259 [FIX] 모바일에서 게시글 작성 버튼 보이게 3차
  kakaobase/src/app/main/page.tsx
  kakaobase/src/widgets/buttons/FloatingButtonGroup.tsx
Labels: FIX

#262 [FIX] 대댓글 작성 시 대댓글 보이도록 유지
  kakaobase/src/features/feeds/comments/stores/recommentFormStateStore.tsx
Labels: FIX

#264 [DESIGN] 하단 고정 컴포넌트 fixed로 변경
  kakaobase/src/app/alarm/page.tsx
  kakaobase/src/app/chat/page.tsx
  kakaobase/src/app/likes/[postType]/[postId]/page.tsx
  kakaobase/src/app/main/page.tsx
  kakaobase/src/app/post/[postId]/page.tsx
  kakaobase/src/app/profile/[userId]/edit/page.tsx
  kakaobase/src/app/profile/[userId]/followers/page.tsx
  kakaobase/src/app/profile/[userId]/followings/page.tsx
  kakaobase/src/features/account/ui/MyPageWrapper.tsx
  kakaobase/src/features/account/ui/edit/EditWrapper.tsx
  kakaobase/src/features/account/ui/edit/RoutingButtons.tsx
  kakaobase/src/features/account/ui/list/CommentList.tsx
  kakaobase/src/features/account/ui/list/LikeList.tsx
  kakaobase/src/features/account/ui/list/PostList.tsx
  kakaobase/src/features/account/ui/password/PasswordEditWrapper.tsx
  kakaobase/src/features/account/ui/withdraw/WithdrawWrapper.tsx
  kakaobase/src/features/chat/ui/ChatList.tsx
  kakaobase/src/features/chat/ui/MessageInput.tsx
  kakaobase/src/features/feeds/comments/ui/CommentInput.tsx
  kakaobase/src/features/feeds/posts/ui/PostList.tsx
  kakaobase/src/widgets/buttons/FloatingButtonGroup.tsx
  kakaobase/src/widgets/navbar/NavBar.tsx
  kakaobase/src/widgets/navbar/NavItem.tsx
Labels: FIX, DESIGN

#267 [FIX] 하단 고정 요소 포지션 수정
  kakaobase/src/app/alarm/page.tsx
  kakaobase/src/app/chat/page.tsx
  kakaobase/src/app/likes/[postType]/[postId]/page.tsx
  kakaobase/src/app/main/page.tsx
  kakaobase/src/app/post/[postId]/page.tsx
  kakaobase/src/app/profile/[userId]/edit/page.tsx
  kakaobase/src/app/profile/[userId]/followers/page.tsx
  kakaobase/src/app/profile/[userId]/followings/page.tsx
  kakaobase/src/features/account/ui/MyPageWrapper.tsx
  kakaobase/src/features/account/ui/password/PasswordEditWrapper.tsx
  kakaobase/src/features/account/ui/withdraw/WithdrawWrapper.tsx
  kakaobase/src/features/chat/ui/MessageInput.tsx
  kakaobase/src/features/feeds/comments/ui/CommentInput.tsx
  kakaobase/src/widgets/navbar/NavBar.tsx
Labels: FIX, DESIGN

#268 [FIX] 모바일에서 CommentInput 안 보이는 문제 해결
  kakaobase/src/app/post/[postId]/page.tsx
  kakaobase/src/features/feeds/comments/ui/CommentInput.tsx
  kakaobase/src/features/feeds/ui/PostCard.tsx
Labels: FIX, DESIGN

#269 [FIX] commentInput 재시도
  kakaobase/src/features/feeds/comments/ui/CommentInput.tsx
  kakaobase/src/features/feeds/comments/ui/RecommentStateBar.tsx
Labels: FIX, DESIGN

#270 [FIX] 채팅 페이지에 다시 네비게이션 바 넣기
  kakaobase/src/app/chat/page.tsx
Labels: FIX

#274 [FEAT] 채팅 로직 구현
  kakaobase/src/features/alarm/hooks/useAlarm.tsx
  kakaobase/src/features/alarm/lib/socket.tsx
  kakaobase/src/features/chat/api/chatList.tsx
  kakaobase/src/features/chat/api/chatQueries.tsx
  kakaobase/src/features/chat/hooks/useMessageForm.tsx
  kakaobase/src/features/chat/stores/chatStore.tsx
  kakaobase/src/features/chat/types/ChatPublishingEvent.tsx
  kakaobase/src/features/chat/types/ChatServerEvent.tsx
  kakaobase/src/features/chat/types/Chats.tsx
  kakaobase/src/features/chat/ui/ChatList.tsx
Labels: FEAT

#273 [REFACTOR] 쿼리 팩토리 반영
  kakaobase/src/app/likes/[postType]/[postId]/page.tsx
  kakaobase/src/features/account/api/accountQueries.tsx
  kakaobase/src/features/account/hooks/list/useMyCommentsHook.tsx
  kakaobase/src/features/account/hooks/list/useMyLikesHook.tsx
  kakaobase/src/features/account/hooks/list/useMyPostsHook.tsx
  kakaobase/src/features/account/hooks/useUserInfo.tsx
  kakaobase/src/features/account/hooks/useUserInfoHook.tsx
  kakaobase/src/features/account/ui/MyPageWrapper.tsx
  kakaobase/src/features/account/ui/list/CommentList.tsx
  kakaobase/src/features/account/ui/list/LikeList.tsx
  kakaobase/src/features/account/ui/list/PostList.tsx
  kakaobase/src/features/feeds/api/comment.tsx
  kakaobase/src/features/feeds/api/feedQueries.tsx
  kakaobase/src/features/feeds/api/list.tsx
  kakaobase/src/features/feeds/api/post.tsx
  kakaobase/src/features/feeds/api/recomment.tsx
  kakaobase/src/features/feeds/comments/api/commentList.tsx
  kakaobase/src/features/feeds/comments/api/recomment.tsx
  kakaobase/src/features/feeds/comments/hooks/useCommentDeleteHook.tsx
  kakaobase/src/features/feeds/comments/hooks/useCommentDetailHook.tsx
  kakaobase/src/features/feeds/comments/hooks/useCommentForm.tsx
  kakaobase/src/features/feeds/comments/hooks/useCommentList.tsx
  kakaobase/src/features/feeds/comments/hooks/useRecommentDeleteHook.tsx
  kakaobase/src/features/feeds/comments/hooks/useRecommentList.tsx
  kakaobase/src/features/feeds/comments/ui/CommentList.tsx
  kakaobase/src/features/feeds/comments/ui/RecommentList.tsx
  kakaobase/src/features/feeds/posts/api/postList.tsx
  kakaobase/src/features/feeds/posts/hooks/useCourseSelectHook.tsx
  kakaobase/src/features/feeds/posts/hooks/usePostDeleteHook.tsx
  kakaobase/src/features/feeds/posts/hooks/usePostDetailHook.tsx
  kakaobase/src/features/feeds/posts/hooks/usePostEditorForm.tsx
  kakaobase/src/features/feeds/posts/hooks/usePostList.tsx
  kakaobase/src/features/feeds/types/postParams.tsx
  kakaobase/src/features/follows/api/followQueries.tsx
  kakaobase/src/features/follows/hooks/useFollowHook.tsx
  kakaobase/src/features/follows/hooks/useFollowersHook.tsx
  kakaobase/src/features/follows/hooks/useFollowingsHook.tsx
  kakaobase/src/features/follows/ui/UserFollowerList.tsx
  kakaobase/src/features/follows/ui/UserFollowingList.tsx
  kakaobase/src/features/likes/api/like.tsx
  kakaobase/src/features/likes/api/likeList.tsx
  kakaobase/src/features/likes/api/likeQueries.tsx
  kakaobase/src/features/likes/hooks/useLikeHook.tsx
  kakaobase/src/features/likes/hooks/useLikeListHook.tsx
  kakaobase/src/features/likes/ui/UserLikeList.tsx
  kakaobase/src/shared/api/queryClient.tsx
  kakaobase/src/widgets/buttons/GoUp.tsx
Labels: REFACTOR

#285 [FIX] 채팅 페이지 스크롤 / 엔터 문제 해결
  kakaobase/src/app/chat/page.tsx
  kakaobase/src/features/chat/api/chatQueries.tsx
  kakaobase/src/features/chat/hooks/useMessageForm.tsx
  kakaobase/src/features/chat/ui/ChatInput.tsx
  kakaobase/src/features/chat/ui/ChatList.tsx
  kakaobase/src/shared/ui/Toast.tsx
Labels: FIX

#287 [CHORE] https 환경 세팅 및 window 제거
  kakaobase/package.json
  kakaobase/server.js
  kakaobase/src/shared/api/api.tsx
Labels: CHORE

#288 [FIX] 배포 서버에서 build 명령어 충돌
  kakaobase/package.json
  kakaobase/server.js
Labels: FIX

#290 Design/#289 phone design
  kakaobase/src/app/alarm/page.tsx
  kakaobase/src/app/chat/page.tsx
  kakaobase/src/app/globals.css
  kakaobase/src/app/post/[postId]/page.tsx
  kakaobase/src/features/chat/hooks/useMessageForm.tsx
  kakaobase/src/features/chat/ui/ChatList.tsx
  kakaobase/src/features/feeds/comments/ui/CommentInput.tsx
  kakaobase/src/features/feeds/comments/ui/RecommentStateBar.tsx
Labels: DESIGN

#291 [FIX] 모바일 디자인 1차 보완
  kakaobase/public/job/RIDI.webp
  kakaobase/public/job/elice.webp
  kakaobase/public/job/visang.webp
  kakaobase/public/void.webp
  kakaobase/src/app/chat/page.tsx
  kakaobase/src/features/alarm/ui/AlarmList.tsx
  kakaobase/src/features/chat/ui/ChatInput.tsx
  kakaobase/src/features/main/data/banners.tsx
  kakaobase/src/features/main/types/Banner.tsx
  kakaobase/src/features/main/ui/Banner.tsx
Labels: FIX

#292 [FIX] 채팅 로직 수정
  kakaobase/src/features/alarm/stores/alarmStore.tsx
Labels: FIX

#295 [REFACTOR] 폰트 2차 적용
  kakaobase/src/app/chat/page.tsx
  kakaobase/src/app/globals.css
  kakaobase/tailwind.config.ts
Labels: REFACTOR

#299 [FIX] 소켓 포함 페이지 변경 및 기타 수정
  kakaobase/src/app/(with-socket)/alarm/page.tsx
  kakaobase/src/app/(with-socket)/chat/page.tsx
  kakaobase/src/app/(with-socket)/layout.tsx
  kakaobase/src/app/(with-socket)/likes/[postType]/[postId]/page.tsx
  kakaobase/src/app/(with-socket)/main/page.tsx
  kakaobase/src/app/(with-socket)/page.tsx
  kakaobase/src/app/(with-socket)/post/[postId]/page.tsx
  kakaobase/src/app/(with-socket)/post/new/page.tsx
  kakaobase/src/app/(with-socket)/profile/[userId]/edit/page.tsx
  kakaobase/src/app/(with-socket)/profile/[userId]/edit/password/page.tsx
  kakaobase/src/app/(with-socket)/profile/[userId]/edit/withdraw/page.tsx
  kakaobase/src/app/(with-socket)/profile/[userId]/followers/page.tsx
  kakaobase/src/app/(with-socket)/profile/[userId]/followings/page.tsx
  kakaobase/src/app/(with-socket)/profile/[userId]/page.tsx
  kakaobase/src/app/layout.tsx
  kakaobase/src/features/account/ui/MyPageWrapper.tsx
  kakaobase/src/features/alarm/stores/alarmStore.tsx
  kakaobase/src/features/alarm/ui/AlarmContainer.tsx
  kakaobase/src/features/alarm/ui/AlarmList.tsx
  kakaobase/src/features/feeds/ui/PostCard.tsx
  kakaobase/src/features/socket/lib/socket.tsx
  kakaobase/src/shared/api/api.tsx
  kakaobase/src/widgets/modal/RequireLoginModal.tsx
Labels: FIX

#305 [ 💜 FE - FIX] CI PR 시 실행 조건 추가, CI/CD 실행 분리
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
Labels: FIX, !HOTFIX

#306 [REFACTOR] 이미지 최적화
  kakaobase/next.config.mjs
  kakaobase/public/logo_square.png
  kakaobase/public/logo_square.svg
  kakaobase/public/logo_title.png
  kakaobase/public/logo_title.svg
  kakaobase/src/app/layout.tsx
  kakaobase/src/app/not-found.tsx
  kakaobase/src/entities/users/ui/UserItem.tsx
  kakaobase/src/features/account/ui/UserInfo.tsx
  kakaobase/src/features/account/ui/edit/ImageInput.tsx
  kakaobase/src/features/alarm/ui/AlarmProfile.tsx
  kakaobase/src/features/chat/ui/BotChat.tsx
  kakaobase/src/features/chat/ui/ChatList.tsx
  kakaobase/src/features/feeds/posts/ui/PostEditor.tsx
  kakaobase/src/features/feeds/ui/UserInfo.tsx
  kakaobase/src/features/feeds/ui/YoutubeFrame.tsx
  kakaobase/src/widgets/header/HeaderMain.tsx
  kakaobase/src/widgets/navbar/NavItemProfile.tsx
Labels: REFACTOR

#278 [REFACTOR] Presentational/Container 디자인 패턴 적용
  kakaobase/src/app/(with-socket)/post/[postId]/page.tsx
  kakaobase/src/app/(with-socket)/profile/[userId]/edit/page.tsx
  kakaobase/src/app/unauthorized/page.tsx
  kakaobase/src/entities/users/ui/UserItem.tsx
  kakaobase/src/features/account/hooks/useWithdrawHook.tsx
  kakaobase/src/features/account/ui/CountInfo.tsx
  kakaobase/src/features/account/ui/MyPageWrapper.tsx
  kakaobase/src/features/account/ui/UserInfo.tsx
  kakaobase/src/features/account/ui/edit/EditWrapper.tsx
  kakaobase/src/features/account/ui/edit/ImageInputContainer.tsx
  kakaobase/src/features/account/ui/edit/ImageLabel.tsx
  kakaobase/src/features/account/ui/edit/RoutingButtons.tsx
  kakaobase/src/features/account/ui/edit/TopArea.tsx
  kakaobase/src/features/account/ui/list/ListRouter.tsx
  kakaobase/src/features/alarm/hooks/useAlarmRouting.tsx
  kakaobase/src/features/auth/hooks/useEmailAuth.tsx
  kakaobase/src/features/auth/hooks/useLoginForm.tsx
  kakaobase/src/features/auth/hooks/useSignupStep1.tsx
  kakaobase/src/features/auth/hooks/useSingupStep2.tsx
  kakaobase/src/features/auth/ui/LoginForm.tsx
  kakaobase/src/features/auth/ui/RoutingButtons.tsx
  kakaobase/src/features/auth/ui/UnauthorizedModal.tsx
  kakaobase/src/features/feeds/comments/hooks/useCommentDeleteHook.tsx
  kakaobase/src/features/feeds/comments/ui/CommentInput.tsx
  kakaobase/src/features/feeds/posts/hooks/usePostDeleteHook.tsx
  kakaobase/src/features/feeds/posts/hooks/usePostEditorForm.tsx
  kakaobase/src/features/feeds/ui/CountsInfo.tsx
  kakaobase/src/features/feeds/ui/PostCard.tsx
  kakaobase/src/features/feeds/ui/PostDetail.tsx
  kakaobase/src/features/feeds/ui/UserInfo.tsx
  kakaobase/src/features/main/ui/PostByCourse.tsx
  kakaobase/src/shared/hooks/useRoutings.tsx
  kakaobase/src/widgets/buttons/GoNewPost.tsx
  kakaobase/src/widgets/header/HeaderLeft.tsx
  kakaobase/src/widgets/navbar/NavItem.tsx
Labels: REFACTOR
