Repository 100-hours-a-week/22-tenten-fe, pull requests merged in 2025-06, with the labels that each got.

#130 [REFACTOR] 텍스트 성능 최적화
  kakaobase/public/fonts/Pretendard-ExtraBold.woff2
  kakaobase/public/fonts/Pretendard-Regular.woff2
  kakaobase/src/app/fonts.tsx
  kakaobase/src/app/globals.css
  kakaobase/src/app/layout.tsx
  kakaobase/src/app/post/[postId]/comment/[commentId]/page.tsx
  kakaobase/src/app/post/[postId]/page.tsx
  kakaobase/src/hooks/post/usePostDetailHook.tsx
  kakaobase/tailwind.config.ts
Labels: REFACTOR

#131 [REFACTOR] 이미지 lcp 최적화
  kakaobase/src/components/post/PostCard.tsx
Labels: REFACTOR

#125 [FEAT] 토큰 재발급
  kakaobase/package.json
  kakaobase/server.js
  kakaobase/src/apis/login.tsx
  kakaobase/src/app/page.tsx
  kakaobase/src/app/post/[postId]/comment/[commentId]/page.tsx
  kakaobase/src/app/post/[postId]/page.tsx
  kakaobase/src/components/common/button/SubmitButton.tsx
  kakaobase/src/components/post/PostCourseSelector.tsx
  kakaobase/src/hooks/post/useDeleteHook.tsx
  kakaobase/src/hooks/post/usePostDetailHook.tsx
  kakaobase/src/hooks/post/usePostEditorForm.tsx
  kakaobase/src/hooks/user/useLoginForm.tsx
  kakaobase/src/hooks/user/useTokenCheckHook.tsx
Labels: FEAT

#135 [FEAT] 프로필 편집 구현
  kakaobase/src/apis/editProfile.tsx
  kakaobase/src/apis/login.tsx
  kakaobase/src/app/profile/[userId]/edit/page.tsx
  kakaobase/src/components/common/loading/LoadingSmall.tsx
  kakaobase/src/components/profile/edit/ImageInput.tsx
  kakaobase/src/components/profile/edit/ReadOnlyUserInfo.tsx
  kakaobase/src/components/profile/edit/RoutingButtons.tsx
  kakaobase/src/components/profile/edit/TopArea.tsx
  kakaobase/src/components/profile/edit/Wrapper.tsx
  kakaobase/src/hooks/post/usePostEditorForm.tsx
  kakaobase/src/hooks/profile/useImageEditHook.tsx
  kakaobase/src/hooks/user/useLoginForm.tsx
  kakaobase/src/schemas/profileImageSchema.tsx
Labels: FEAT

#139 [FEAT] 회원 탈퇴 구현
  kakaobase/src/apis/withdraw.tsx
  kakaobase/src/app/profile/[userId]/edit/withdraw/page.tsx
  kakaobase/src/components/profile/withdraw/Wrapper.tsx
  kakaobase/src/hooks/profile/useWithdrawHook.tsx
Labels: FEAT

#141 [FEAT] 마이페이지 ui 구현
  kakaobase/src/apis/login.tsx
  kakaobase/src/app/profile/[userId]/page.tsx
  kakaobase/src/components/common/NavBar.tsx
  kakaobase/src/components/common/button/SubmitButton.tsx
  kakaobase/src/components/profile/CountInfo.tsx
  kakaobase/src/components/profile/Toggle.tsx
  kakaobase/src/components/profile/UserInfo.tsx
  kakaobase/src/components/profile/Wrapper.tsx
  kakaobase/src/hooks/user/useLoginForm.tsx
Labels: FEAT

#143 [FEAT] 좋아요 등록 유저 목록 조회 페이지 ui
  kakaobase/src/apis/likeList.tsx
  kakaobase/src/app/likes/[postType]/[postId]/page.tsx
  kakaobase/src/components/likeFollow/UserItem.tsx
  kakaobase/src/components/likeFollow/UserList.tsx
  kakaobase/src/components/post/CountsInfo.tsx
Labels: FEAT

#144 [FEAT] 팔로잉/팔로워 목록
  kakaobase/src/apis/follow.tsx
  kakaobase/src/app/profile/[userId]/followers/page.tsx
  kakaobase/src/app/profile/[userId]/followings/page.tsx
  kakaobase/src/components/likeFollow/UserList.tsx
  kakaobase/src/components/profile/CountInfo.tsx
  kakaobase/src/components/profile/Wrapper.tsx
Labels: FEAT

#146 [FEAT/FIX] ui 디테일 수정
  kakaobase/package-lock.json
  kakaobase/package.json
  kakaobase/src/components/common/Modal.tsx
  kakaobase/src/components/common/button/HandleButton.tsx
  kakaobase/src/components/post/list/PostList.tsx
  kakaobase/src/components/profile/CountInfo.tsx
  kakaobase/src/components/profile/QR/CopyUrl.tsx
  kakaobase/src/components/profile/QR/ProfileModal.tsx
  kakaobase/src/components/profile/QR/QrCode.tsx
  kakaobase/src/components/profile/Toggle.tsx
  kakaobase/src/components/profile/UserInfo.tsx
  kakaobase/src/components/profile/Wrapper.tsx
Labels: FEAT, FIX, CHORE

#148 [FEAT] 토스트 추가
  kakaobase/src/apis/postList.tsx
  kakaobase/src/app/ToastContext.tsx
  kakaobase/src/app/providers.tsx
  kakaobase/src/components/common/Toast.tsx
  kakaobase/src/components/post/UserInfo.tsx
  kakaobase/src/components/profile/QR/CopyUrl.tsx
  kakaobase/src/components/profile/edit/ImageInput.tsx
  kakaobase/src/hooks/auth/useEmailAuth.tsx
  kakaobase/src/hooks/post/comment/useCommentForm.tsx
  kakaobase/src/hooks/post/useDeleteHook.tsx
  kakaobase/src/hooks/post/usePostDetailHook.tsx
  kakaobase/src/hooks/post/usePostEditorForm.tsx
  kakaobase/src/hooks/profile/useImageEditHook.tsx
  kakaobase/src/hooks/profile/useWithdrawHook.tsx
  kakaobase/src/hooks/user/useLoginForm.tsx
  kakaobase/src/hooks/user/usePasswordStep.tsx
  kakaobase/src/hooks/user/useSingupStep2.tsx
  kakaobase/src/hooks/user/useTokenCheckHook.tsx
Labels: FEAT

#150 [FEAT] 프로필 편집/탈퇴 로직 구현
  kakaobase/src/apis/editProfile.tsx
  kakaobase/src/apis/login.tsx
  kakaobase/src/components/profile/QR/CopyUrl.tsx
  kakaobase/src/components/profile/edit/ImageInput.tsx
  kakaobase/src/components/profile/edit/TopArea.tsx
  kakaobase/src/components/profile/edit/Wrapper.tsx
  kakaobase/src/hooks/auth/useEmailAuth.tsx
  kakaobase/src/hooks/profile/useGithubEditHook.tsx
  kakaobase/src/hooks/profile/useImageEditHook.tsx
  kakaobase/src/hooks/profile/useWithdrawHook.tsx
  kakaobase/src/hooks/user/useLoginForm.tsx
  kakaobase/src/schemas/githubSchema.tsx
  kakaobase/src/schemas/signupStep2Schema.tsx
Labels: FEAT, FIX

#154 [FIX] 깃허브 스키마 통합
  kakaobase/src/schemas/githubSchema.tsx
  kakaobase/src/schemas/signupStep2Schema.tsx
Labels: FIX, REFACTOR

#166 [FIX] 댓글에서 post id 추적
  kakaobase/src/apis/commentList.tsx
  kakaobase/src/components/post/PostCard.tsx
  kakaobase/src/lib/mapPost.tsx
  kakaobase/src/stores/postType.tsx
Labels: FIX

#171 [FIX] 토스트 로직 제거
  kakaobase/src/apis/api.tsx
Labels: FIX

#172 [FIX] 팔로잉/팔로워 부분 수정
  kakaobase/src/components/social/UserItem.tsx
  kakaobase/src/hooks/social/useFollowersHook.tsx
  kakaobase/src/hooks/social/useFollowingsHook.tsx
Labels: FIX

#173 [REFACTOR] localStorage 제거
  kakaobase/src/apis/login.tsx
  kakaobase/src/apis/post.tsx
  kakaobase/src/components/common/NavBar.tsx
  kakaobase/src/components/post/PostCourseSelector.tsx
  kakaobase/src/components/post/PostEditor.tsx
  kakaobase/src/components/profile/Wrapper.tsx
  kakaobase/src/hooks/post/list/usePostList.tsx
  kakaobase/src/hooks/post/useCourseSelectHook.tsx
  kakaobase/src/hooks/post/useDeleteHook.tsx
  kakaobase/src/hooks/post/usePostDetailHook.tsx
  kakaobase/src/hooks/post/usePostEditorForm.tsx
  kakaobase/src/hooks/profile/useImageEditHook.tsx
  kakaobase/src/hooks/user/useLoginForm.tsx
  kakaobase/src/lib/Course.tsx
  kakaobase/src/lib/postType.tsx
  kakaobase/src/stores/userStore.tsx
Labels: REFACTOR

#176 [REFACTOR] 스키마 리팩토링
  kakaobase/src/schemas/emailAuthSchema.tsx
  kakaobase/src/schemas/emailSchema.tsx
  kakaobase/src/schemas/imageSchema.tsx
  kakaobase/src/schemas/loginSchema.tsx
  kakaobase/src/schemas/passwordConfirmSchema.tsx
  kakaobase/src/schemas/passwordSchema.tsx
  kakaobase/src/schemas/postSchema.tsx
  kakaobase/src/schemas/profileImageSchema.tsx
Labels: FIX, REFACTOR

#181 [FIX] 좋아요, 팔로우, 팔로잉 목록 스크롤 해결
  kakaobase/src/components/social/UserFollowerList.tsx
  kakaobase/src/components/social/UserFollowingList.tsx
  kakaobase/src/components/social/UserLikeList.tsx
  kakaobase/src/hooks/social/useFollowersHook.tsx
  kakaobase/src/hooks/social/useFollowingsHook.tsx
  kakaobase/src/hooks/social/useLikeListHook.tsx
Labels: FIX

#188 [HOTFIX] 팔로우 관련 수정
  kakaobase/src/components/profile/CountInfo.tsx
  kakaobase/src/hooks/social/useFollowersHook.tsx
  kakaobase/src/hooks/social/useFollowingsHook.tsx
  kakaobase/src/hooks/user/useFollowHook.tsx
Labels: !HOTFIX

#190 [FEAT] CI/CD를 위한 workflow/deploy.ym. & Dockerfile 추가
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
  kakaobase/Dockerfile
  kakaobase/appspec.yml
  kakaobase/scripts/deploy.sh
  kakaobase/scripts/health_check.sh
Labels: FEAT

#203 [HOTFIX ] Dockerfile, workflows의 환경변수 수정
  kakaobase/Dockerfile
Labels: !HOTFIX

#204 [FEAT] 댓글/대댓글 통합
  .DS_Store
  README.md
  kakaobase/src/app/post/[postId]/comment/[commentId]/page.tsx
  kakaobase/src/features/feeds/comments/hooks/useCommentForm.tsx
  kakaobase/src/features/feeds/comments/hooks/useCommentOrRecomment.tsx
  kakaobase/src/features/feeds/comments/hooks/useRecommentDeleteHook.tsx
  kakaobase/src/features/feeds/comments/stores/commentFormStateStore.tsx
  kakaobase/src/features/feeds/comments/ui/CommentInput.tsx
  kakaobase/src/features/feeds/comments/ui/RecommentList.tsx
  kakaobase/src/features/feeds/ui/CountsInfo.tsx
  kakaobase/src/features/feeds/ui/PostCard.tsx
  kakaobase/src/shared/hooks/ToastContext.tsx
Labels: FEAT

#206 [FIX] ui 수정
  kakaobase/package-lock.json
  kakaobase/package.json
  kakaobase/src/app/alarm/page.tsx
  kakaobase/src/app/chat/page.tsx
  kakaobase/src/app/login/page.tsx
  kakaobase/src/app/page.tsx
  kakaobase/src/app/post/[postId]/page.tsx
  kakaobase/src/app/post/new/page.tsx
  kakaobase/src/app/profile/[userId]/edit/page.tsx
  kakaobase/src/app/profile/[userId]/edit/password/page.tsx
  kakaobase/src/app/profile/[userId]/edit/withdraw/page.tsx
  kakaobase/src/app/profile/[userId]/followers/page.tsx
  kakaobase/src/app/profile/[userId]/followings/page.tsx
  kakaobase/src/app/signup/step1/page.tsx
  kakaobase/src/app/signup/step2/page.tsx
  kakaobase/src/features/account/ui/MyPageWrapper.tsx
  kakaobase/src/features/account/ui/edit/EditWrapper.tsx
  kakaobase/src/features/account/ui/password/PasswordEditWrapper.tsx
  kakaobase/src/features/account/ui/withdraw/WithdrawWrapper.tsx
  kakaobase/src/features/auth/ui/LoginForm.tsx
  kakaobase/src/features/auth/ui/SignupStep1Form.tsx
  kakaobase/src/features/auth/ui/SignupStep2Form.tsx
  kakaobase/src/features/feeds/posts/hooks/usePostList.tsx
  kakaobase/src/features/feeds/posts/ui/PostCourseSelector.tsx
  kakaobase/src/features/feeds/ui/CountsInfo.tsx
  kakaobase/src/features/feeds/ui/ListRouter.tsx
  kakaobase/src/features/feeds/ui/PostCard.tsx
  kakaobase/src/features/likes/ui/UserLikeList.tsx
  kakaobase/src/shared/lib/courseMap.tsx
  kakaobase/src/shared/types/Course.tsx
  kakaobase/src/widgets/header/Header.tsx
  kakaobase/src/widgets/header/HeaderMain.tsx
  kakaobase/src/widgets/navbar/NavBar.tsx
  kakaobase/src/widgets/navbar/NavItem.tsx
  kakaobase/src/widgets/navbar/NavItemProfile.tsx
  kakaobase/tailwind.config.ts
Labels: FIX, DESIGN

#208 [HOTFIX] 빌드 에러 수정
  kakaobase/src/features/feeds/comments/ui/RecommentList.tsx
Labels: CHORE, !HOTFIX

#217 [MERGE] FE CI/CD 수정
  .github/workflows/dev-deploy.yml
Labels: !HOTFIX

#219 [FEAT] 메인 페이지 구현 및 라우팅 재설정 및 백엔드 오류 확인
  kakaobase/public/teams/01.webp
  kakaobase/public/teams/02.png
  kakaobase/public/teams/03.webp
  kakaobase/public/teams/04.png
  kakaobase/public/teams/05.webp
  kakaobase/public/teams/06.webp
  kakaobase/public/teams/07.jpeg
  kakaobase/public/teams/08.webp
  kakaobase/public/teams/09.webp
  kakaobase/public/teams/10.webp
  kakaobase/public/teams/11.jpg
  kakaobase/public/teams/12.png
  kakaobase/public/teams/13.webp
  kakaobase/public/teams/14.webp
  kakaobase/public/teams/15.webp
  kakaobase/public/teams/16.webp
  kakaobase/public/teams/17.webp
  kakaobase/public/teams/18.webp
  kakaobase/public/teams/19.png
  kakaobase/public/teams/20.png
  kakaobase/public/teams/21.webp
  kakaobase/src/app/main/page.tsx
  kakaobase/src/app/page.tsx
  kakaobase/src/app/post/[postId]/page.tsx
  kakaobase/src/features/account/ui/MyPageWrapper.tsx
  kakaobase/src/features/banner/data/banners.tsx
  kakaobase/src/features/banner/hooks/ useBannerHook.tsx
  kakaobase/src/features/banner/types/Banner.tsx
  kakaobase/src/features/banner/ui/Banner.tsx
  kakaobase/src/features/feeds/comments/hooks/useCommentDetailHook.tsx
  kakaobase/src/features/feeds/posts/api/post.tsx
  kakaobase/src/features/feeds/posts/hooks/useCourseSelectHook.tsx
  kakaobase/src/features/feeds/posts/hooks/usePostDeleteHook.tsx
  kakaobase/src/features/feeds/posts/hooks/usePostEditorForm.tsx
  kakaobase/src/features/feeds/posts/ui/PostCourseSelector.tsx
  kakaobase/src/features/feeds/ui/CountsInfo.tsx
  kakaobase/src/features/feeds/ui/PostCard.tsx
  kakaobase/src/features/main/ui/PostByCourse.tsx
  kakaobase/src/shared/types/Course.tsx
  kakaobase/src/shared/ui/button/GoUp.tsx
  kakaobase/src/widgets/navbar/NavBar.tsx
  kakaobase/src/widgets/navbar/NavItem.tsx
  kakaobase/src/widgets/navbar/NavItemPost.tsx
  kakaobase/src/widgets/navbar/NavItemProfile.tsx
  kakaobase/tailwind.config.ts
Labels: FEAT

#221 [FEAT] SEO 적용
  kakaobase/public/logo.svg
  kakaobase/public/test_image.jpg
  kakaobase/public/test_profile.jpg
  kakaobase/src/app/layout.tsx
Labels: FEAT

#225 [HOTFIX] dev-deploy.yml type check를 위한 package.json 수정
  .github/workflows/dev-deploy.yml
  kakaobase/package.json
Labels: !HOTFIX

#227 [FIX] 좋아요 개수 서버와 상태 연결
  kakaobase/src/features/likes/hooks/useLikeHook.tsx
Labels: FIX

#231 [FIX] 로그인 안 된 사용자를 위한 페이지 구현
  kakaobase/src/app/unauthorized/page.tsx
  kakaobase/src/features/feeds/posts/hooks/usePostEditorForm.tsx
  kakaobase/src/shared/api/api.tsx
Labels: FEAT, FIX

#235 [FIX] 로그인 안 된 사용자 마이페이지 접근 시 페이지 이동 처리
  kakaobase/src/features/account/ui/MyPageWrapper.tsx
  kakaobase/src/widgets/navbar/NavItemProfile.tsx
Labels: FIX

#236 [MERGE] dev -> main 오류 해결
  kakaobase/src/features/account/ui/MyPageWrapper.tsx
  kakaobase/src/widgets/navbar/NavItemProfile.tsx
Labels: CHORE

#237 [FEAT] 알림 페이지 ui 구현
  kakaobase/src/app/alarm/page.tsx
  kakaobase/src/app/chat/page.tsx
  kakaobase/src/app/main/page.tsx
  kakaobase/src/app/unauthorized/page.tsx
  kakaobase/src/features/alarm/types/Alarm.tsx
  kakaobase/src/features/alarm/ui/AlarmItem.tsx
  kakaobase/src/features/alarm/ui/AlarmList.tsx
  kakaobase/src/features/follows/ui/FollowButtonSmall.tsx
  kakaobase/src/shared/ui/button/GoUp.tsx
  kakaobase/src/widgets/buttons/FloatingButtonGroup.tsx
  kakaobase/src/widgets/buttons/GoNewPost.tsx
  kakaobase/src/widgets/buttons/GoUp.tsx
  kakaobase/src/widgets/navbar/NavBar.tsx
  kakaobase/src/widgets/navbar/NavItem.tsx
  kakaobase/src/widgets/navbar/NavItemPost.tsx
  kakaobase/src/widgets/navbar/NavItemProfile.tsx
Labels: FEAT
